In [1]:
import pandas as pd

In [2]:
print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

In [3]:
data = {
    "Player": ["LeBron James", "Stephen Curry", "Kevin Durant"],
    "Points": [25, 28, 27],
    "Assists": [8, 6, 5]
}

df = pd.DataFrame(data)

In [4]:
df

          Player  Points  Assists
0   LeBron James      25        8
1  Stephen Curry      28        6
2   Kevin Durant      27        5

In [5]:
df.describe()

          Points   Assists
count   3.000000  3.000000
mean   26.666667  6.333333
std     1.527525  1.527525
min    25.000000  5.000000
25%    26.000000  5.500000
50%    27.000000  6.000000
75%    27.500000  7.000000
max    28.000000  8.000000

In [6]:
df.sort_values(by="Points", ascending=False)

          Player  Points  Assists
1  Stephen Curry      28        6
2   Kevin Durant      27        5
0   LeBron James      25        8