In [1]:
import pandas as pd

In [2]:
print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

In [3]:
data = {
    "Player": ["LeBron James", "Stephen Curry", "Kevin Durant"],
    "Points": [25, 28, 27],
    "Assists": [8, 6, 5]
}

df = pd.DataFrame(data)

In [4]:
df

          Player  Points  Assists
0   LeBron James      25        8
1  Stephen Curry      28        6
2   Kevin Durant      27        5

In [5]:
df.describe()

          Points   Assists
count   3.000000  3.000000
mean   26.666667  6.333333
std     1.527525  1.527525
min    25.000000  5.000000
25%    26.000000  5.500000
50%    27.000000  6.000000
75%    27.500000  7.000000
max    28.000000  8.000000

In [6]:
df.sort_values(by="Points", ascending=False)

          Player  Points  Assists
1  Stephen Curry      28        6
2   Kevin Durant      27        5
0   LeBron James      25        8

In [7]:
#Now do it with real data

In [8]:
from data.nbaDataImport import load_nba_games

In [9]:
#Load games from sql -> dataframe

In [10]:
nba_data = load_nba_games()

         id   game_date  season  home_team_id         home_team_name  \
0  18446819  2025-10-21    2025            21  Oklahoma City Thunder
1  18446820  2025-10-21    2025            14     Los Angeles Lakers
2  18446821  2025-10-22    2025            20        New York Knicks
3  18446822  2025-10-22    2025             7       Dallas Mavericks
4  18446823  2025-10-22    2025             4      Charlotte Hornets

   visitor_team_id      visitor_team_name  home_team_score  \
0               11        Houston Rockets              125
1               10  Golden State Warriors              109
2                6    Cleveland Cavaliers              119
3               27      San Antonio Spurs               92
4                3          Brooklyn Nets              136

   visitor_team_score  postseason
0                 124       False
1                 119       False
2                 111       False
3                 125       False
4                 117       False
(2643, 10)

In [11]:
nba_data.describe()

,id,season,home_team_id,visitor_team_id,home_team_score,visitor_team_score
count,2.643000e+03,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000
mean,1.740806e+07,2024.500189,15.491487,15.479001,115.199773,113.377601
std,1.505938e+06,0.500095,8.570599,8.575434,12.840466,12.943088
min,1.590744e+07,2024.000000,1.000000,1.000000,77.000000,66.000000
25%,1.590810e+07,2024.000000,8.000000,8.000000,106.000000,105.000000
50%,1.844682e+07,2025.000000,16.000000,16.000000,115.000000,113.000000
75%,1.844748e+07,2025.000000,23.000000,23.000000,124.000000,122.000000
max,2.171614e+07,2025.000000,30.000000,30.000000,157.000000,162.000000

In [12]:
# look at scores

In [13]:
nba_data[["home_team_score","visitor_team_score"]].describe()

       home_team_score  visitor_team_score
count      2643.000000         2643.000000
mean        115.199773          113.377601
std          12.840466           12.943088
min          77.000000           66.000000
25%         106.000000          105.000000
50%         115.000000          113.000000
75%         124.000000          122.000000
max         157.000000          162.000000

In [14]:
# check the basics of the data

In [15]:
nba_data.shape

(2643, 10)

In [16]:
#check the top of the table

In [17]:
nba_data.head()

,id,game_date,season,home_team_id,home_team_name,visitor_team_id,visitor_team_name,home_team_score,visitor_team_score,postseason
0,18446819,2025-10-21,2025,21,Oklahoma City Thunder,11,Houston Rockets,125,124,False
1,18446820,2025-10-21,2025,14,Los Angeles Lakers,10,Golden State Warriors,109,119,False
2,18446821,2025-10-22,2025,20,New York Knicks,6,Cleveland Cavaliers,119,111,False
3,18446822,2025-10-22,2025,7,Dallas Mavericks,27,San Antonio Spurs,92,125,False
4,18446823,2025-10-22,2025,4,Charlotte Hornets,3,Brooklyn Nets,136,117,False

In [18]:
#check for nulls

In [19]:
nba_data.isnull().sum()

id                    0
game_date             0
season                0
home_team_id          0
home_team_name        0
visitor_team_id       0
visitor_team_name     0
home_team_score       0
visitor_team_score    0
postseason            0
dtype: int64

In [20]:
#organzie by season

In [21]:
nba_data.groupby("season")[["home_team_score","visitor_team_score"]].describe()

       home_team_score                                                    \
                 count        mean        std   min    25%    50%    75%
season
2024            1321.0  114.408781  12.655136  79.0  105.0  115.0  123.0
2025            1322.0  115.990166  12.979716  77.0  107.0  116.0  125.0

              visitor_team_score                                             \
          max              count        mean        std   min    25%    50%
season
2024    155.0             1321.0  112.542014  12.877156  67.0  104.0  113.0
2025    157.0             1322.0  114.212557  12.959766  66.0  105.0  114.0


          75%    max
season
2024    121.0  162.0
2025    123.0  157.0